# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nimat
# "service" is the name of this project. This will also be added to your AWS resource names.
service: order

provider:
  name: aws
  runtime: nodejs24.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - ses:SendEmail
      Resource:
        - fn::GetAtt: [OrdersTable, Arn]
        - fn::GetAtt: [OrderQueue, Arn]
        - arn:aws:ses:us-east-1:* # do not use this in production, restrict to your identity
  environment:
    ORDERS_TABLE: Orders
    ORDER_QUEUE_URL:
      Ref: OrderQueue
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    OrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: OrderQueue
    OrderServiceEmailIdentity:
      Type: AWS::SES::EmailIdentity
      Properties:
        EmailIdentity: "nimatullah.razmjo@gmail.com"
functions:
  placeOrder:
    handler: handlers/placeOrder.placeOrder
    events:
      - httpApi:
          path: /place-order
          method: post
  processOOrder:
    handler: handlers/processOrder.processOrder
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - OrderQueue
              - Arn
