org: nimat

service: product

provider:
  name: aws
  runtime: nodejs24.x
  region: us-east-1
  httpApi:
    authorizers:
      myCognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_1Be9nNzWD
        audience:
          - 4up61llpcp8spd9r1k3n52a69t
  environment:
    BUCKET_NAME: product-nimat-images
    DYNAMODB_TABLE: Products
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:720180693865:ProductCleanupTopic
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::product-nimat-images/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:Scan"
        - "dynamodb:DeleteItem"
      Resource:
        - "arn:aws:dynamodb:us-east-1:*:table/Products"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - "arn:aws:sns:us-east-1:720180693865:ProductCleanupTopic"
resources:
  Resources:
    ProductImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: product-nimat-images
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    ProductCleanupTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ProductCleanupTopic
    ProductCleanupTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:us-east-1:720180693865:ProductCleanupTopic
        Protocol: email
        Endpoint: ni.razmjo@gmail.com

functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post
          authorizer:
            name: myCognitoAuthorizer
  updateProductImage:
    handler: handlers/updateProductImage.updateProductImage
    events:
      - s3:
          bucket: product-nimat-images
          event: s3:ObjectCreated:Put
          existing: true
  cleanupProduct:
    handler: handlers/cleanupProduct.cleanupProduct
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true
  getApprovedProducts:
    handler: handlers/getApprovedProducts.getApprovedProducts
    events:
      - httpApi:
          path: /approved-products
          method: get
